// Wave 04 seed. Four distinct money concepts, never blurred:
//   received  = cash in from donations
//   allocated = money formally assigned to a fund (never exceeds received)
//   budget    = what the programme plans to spend (may exceed allocation -> funding gap)
//   spent     = expenses accepted into the ledger (already incurred, then approved)
// Evidence items carry `checked`: attached is not the same as checked by our team.
export const donations = [
 { "id": "don-2026-041", "donor": "BrightWorks Bangladesh Ltd", "type": "Corporate", "amount": 1500000, "date": "12 Aug 2026", "method": "Bank transfer", "restricted": "ai-digital-skills", "receipt": "GS-RCP-2026-0041", "acknowledged": true },
 { "id": "don-2026-040", "donor": "Rahman Family Foundation", "type": "Foundation", "amount": 2500000, "date": "05 Aug 2026", "method": "Bank transfer", "restricted": "education-career-readiness", "receipt": "GS-RCP-2026-0040", "acknowledged": true },
 { "id": "don-2026-039", "donor": "Tasnim Haque", "type": "Individual", "amount": 50000, "date": "02 Aug 2026", "method": "bKash", "restricted": null, "receipt": "GS-RCP-2026-0039", "acknowledged": true },
 { "id": "don-2026-038", "donor": "Anonymous donor", "type": "Individual", "amount": 25000, "date": "28 Jul 2026", "method": "bKash", "restricted": null, "receipt": "GS-RCP-2026-0038", "acknowledged": false },
 { "id": "don-2026-037", "donor": "Delta Textiles CSR", "type": "Corporate", "amount": 900000, "date": "20 Jul 2026", "method": "Cheque", "restricted": "youth-empowerment", "receipt": "GS-RCP-2026-0037", "acknowledged": true },
 { "id": "don-2026-036", "donor": "Nagorik Trust", "type": "Foundation", "amount": 1200000, "date": "08 Jul 2026", "method": "Bank transfer", "restricted": "community-development", "receipt": "GS-RCP-2026-0036", "acknowledged": true },
 { "id": "don-2026-035", "donor": "Arif Chowdhury", "type": "Individual", "amount": 15000, "date": "01 Jul 2026", "method": "Card", "restricted": null, "receipt": "GS-RCP-2026-0035", "acknowledged": true },
 { "id": "don-2026-034", "donor": "TechHub Dhaka", "type": "Corporate", "amount": 600000, "date": "18 Jun 2026", "method": "Bank transfer", "restricted": "innovation-social-good", "receipt": "GS-RCP-2026-0034", "acknowledged": true }
];

export const funds = [
 { "id": "fnd-education", "programSlug": "education-career-readiness", "program": "Education & Career Readiness", "budget": 2200000, "allocated": 2200000, "project": "Career Launch 2026" },
 { "id": "fnd-digital", "programSlug": "ai-digital-skills", "program": "AI & Digital Skills Development", "budget": 1450000, "allocated": 1450000, "project": "Digital Bangladesh Skills Drive" },
 { "id": "fnd-youth", "programSlug": "youth-empowerment", "program": "Youth Empowerment", "budget": 850000, "allocated": 850000, "project": "Youth Futures 2026" },
 { "id": "fnd-community", "programSlug": "community-development", "program": "Community Development", "budget": 1000000, "allocated": 1000000, "project": "Khulna Ward Scorecard 2026" },
 { "id": "fnd-innovation", "programSlug": "innovation-social-good", "program": "Innovation for Social Good", "budget": 800000, "allocated": 560000, "project": "Open Impact Tools" },
 { "id": "fnd-operations", "programSlug": "operations", "program": "Operations & Administration", "budget": 620000, "allocated": 620000, "project": "Running the organisation" }
];

export const expenses = [
 { "id": "exp-2026-118", "fundId": "fnd-education", "item": "Venue hire — Career Bootcamp, 4 weeks", "amount": 420000, "date": "10 Jun 2026", "payee": "Dhaka Community Hall", "status": "approved", "approvedBy": "Executive Director", "evidence": [{ "label": "Invoice DCH-4471", "checked": true }, { "label": "Bank debit advice", "checked": true }], "missionId": null, "impactId": "imp-career-bootcamp-2026" },
 { "id": "exp-2026-117", "fundId": "fnd-education", "item": "Trainer stipends (6 trainers)", "amount": 360000, "date": "12 Jun 2026", "payee": "6 payees", "status": "approved", "approvedBy": "Executive Director", "evidence": [{ "label": "Signed stipend register", "checked": true }, { "label": "Bank transfer list", "checked": true }], "missionId": null, "impactId": "imp-career-bootcamp-2026" },
 { "id": "exp-2026-116", "fundId": "fnd-education", "item": "Printed workbooks (120 sets)", "amount": 96000, "date": "02 Jun 2026", "payee": "Nabin Press", "status": "approved", "approvedBy": "Programs Lead", "evidence": [{ "label": "Invoice NP-2213", "checked": true }, { "label": "Delivery note", "checked": false }], "missionId": null, "impactId": "imp-career-bootcamp-2026" },
 { "id": "exp-2026-115", "fundId": "fnd-digital", "item": "Laptops for training labs (8 units)", "amount": 640000, "date": "22 May 2026", "payee": "Byte Solutions", "status": "approved", "approvedBy": "Executive Director", "evidence": [{ "label": "Invoice BS-8891", "checked": true }, { "label": "Asset register entry", "checked": true }, { "label": "Delivery photographs", "checked": true }], "missionId": null, "impactId": "imp-ai-literacy-2026" },
 { "id": "exp-2026-114", "fundId": "fnd-digital", "item": "Workshop travel — 8 districts", "amount": 186000, "date": "28 May 2026", "payee": "Various", "status": "approved", "approvedBy": "Programs Lead", "evidence": [{ "label": "Travel claim forms", "checked": true }, { "label": "Ticket copies", "checked": false }], "missionId": null, "impactId": "imp-ai-literacy-2026" },
 { "id": "exp-2026-113", "fundId": "fnd-youth", "item": "Micro-grants disbursed (12 ventures)", "amount": 600000, "date": "18 Apr 2026", "payee": "12 grantees", "status": "approved", "approvedBy": "Executive Director", "evidence": [{ "label": "Grant agreements (12)", "checked": true }, { "label": "Disbursement receipts", "checked": true }], "missionId": null, "impactId": "imp-youth-bootcamp-2026" },
 { "id": "exp-2026-112", "fundId": "fnd-youth", "item": "Bootcamp catering, Rajshahi", "amount": 118000, "date": "15 Apr 2026", "payee": "Padma Caterers", "status": "approved", "approvedBy": "Programs Lead", "evidence": [{ "label": "Invoice PC-331", "checked": true }], "missionId": "msn-rajshahi-youth-01", "impactId": "imp-youth-bootcamp-2026" },
 { "id": "exp-2026-111", "fundId": "fnd-community", "item": "Survey materials & field kits", "amount": 74000, "date": "18 Aug 2026", "payee": "Rupsha Supplies", "status": "approved", "approvedBy": "Programs Lead", "evidence": [{ "label": "Invoice RS-129", "checked": true }, { "label": "Field photographs", "checked": true }], "missionId": "msn-khulna-community-01", "impactId": "imp-khulna-survey-2026" },
 { "id": "exp-2026-110", "fundId": "fnd-community", "item": "Flood relief packs (400 families)", "amount": 520000, "date": "26 Aug 2026", "payee": "Sylhet Wholesale", "status": "pending", "approvedBy": null, "evidence": [{ "label": "Quotation SW-902", "checked": false }], "missionId": "msn-sylhet-flood-01", "impactId": null },
 { "id": "exp-2026-109", "fundId": "fnd-innovation", "item": "Cloud hosting, 12 months", "amount": 144000, "date": "05 Jul 2026", "payee": "CloudBD", "status": "approved", "approvedBy": "Executive Director", "evidence": [{ "label": "Annual invoice CB-7712", "checked": true }], "missionId": null, "impactId": "imp-innovation-lab-2026" },
 { "id": "exp-2026-104", "fundId": "fnd-innovation", "item": "Prototype hardware — sensors & tablets", "amount": 96000, "date": "14 Jul 2026", "payee": "Byte Solutions", "status": "approved", "approvedBy": "Programs Lead", "evidence": [], "missionId": null, "impactId": "imp-innovation-lab-2026" },
 { "id": "exp-2026-108", "fundId": "fnd-innovation", "item": "Designer contract — accessibility audit", "amount": 90000, "date": "12 Jul 2026", "payee": "Arif Chowdhury", "status": "pending", "approvedBy": null, "evidence": [{ "label": "Contract draft", "checked": false }], "missionId": null, "impactId": null },
 { "id": "exp-2026-107", "fundId": "fnd-operations", "item": "Office rent, Q3", "amount": 270000, "date": "01 Jul 2026", "payee": "Gulshan Properties", "status": "approved", "approvedBy": "Executive Director", "evidence": [{ "label": "Lease agreement", "checked": true }, { "label": "Rent receipt Q3", "checked": true }], "missionId": null, "impactId": null },
 { "id": "exp-2026-106", "fundId": "fnd-operations", "item": "Accounting & audit fees", "amount": 165000, "date": "20 Jun 2026", "payee": "Hoque & Co.", "status": "approved", "approvedBy": "Executive Director", "evidence": [{ "label": "Invoice HC-556", "checked": true }, { "label": "Audit engagement letter", "checked": true }], "missionId": null, "impactId": null },
 { "id": "exp-2026-105", "fundId": "fnd-operations", "item": "Platform & communications tools", "amount": 82000, "date": "08 Jun 2026", "payee": "Various SaaS", "status": "approved", "approvedBy": "Programs Lead", "evidence": [{ "label": "Card statements", "checked": true }, { "label": "Vendor receipts", "checked": false }], "missionId": null, "impactId": null }
];
