/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FundRouteImport } from './routes/fund'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MeRouteImport } from './routes/me'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PartnerRoomRouteImport } from './routes/partner-room'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ChaptersIndexRouteImport } from './routes/chapters/index'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters/$chapterId'
import { Route as ChaptersStartRouteImport } from './routes/chapters/start'
import { Route as MissionsIndexRouteImport } from './routes/missions/index'
import { Route as MissionsMissionIdRouteImport } from './routes/missions/$missionId'
import { Route as PartnersPartnerIdRouteImport } from './routes/partners/$partnerId'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PeopleVolunteerIdRouteImport } from './routes/people/$volunteerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FundRoute = FundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoomRoute = PartnerRoomRouteImport.update({
  id: '/partner-room',
  path: '/partner-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersStartRoute = ChaptersStartRouteImport.update({
  id: '/chapters/start',
  path: '/chapters/start',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsMissionIdRoute = MissionsMissionIdRouteImport.update({
  id: '/missions/$missionId',
  path: '/missions/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersPartnerIdRoute = PartnersPartnerIdRouteImport.update({
  id: '/partners/$partnerId',
  path: '/partners/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleVolunteerIdRoute = PeopleVolunteerIdRouteImport.update({
  id: '/people/$volunteerId',
  path: '/people/$volunteerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/fund': typeof FundRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/me': typeof MeRoute
  '/partner': typeof PartnerRoute
  '/partner-room': typeof PartnerRoomRoute
  '/programs': typeof ProgramsRoute
  '/studio': typeof StudioRoute
  '/transparency': typeof TransparencyRoute
  '/trust': typeof TrustRoute
  '/verify': typeof VerifyRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/chapters/start': typeof ChaptersStartRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/people/$volunteerId': typeof PeopleVolunteerIdRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/fund': typeof FundRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/me': typeof MeRoute
  '/partner': typeof PartnerRoute
  '/partner-room': typeof PartnerRoomRoute
  '/programs': typeof ProgramsRoute
  '/studio': typeof StudioRoute
  '/transparency': typeof TransparencyRoute
  '/trust': typeof TrustRoute
  '/verify': typeof VerifyRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/chapters/start': typeof ChaptersStartRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/people/$volunteerId': typeof PeopleVolunteerIdRoute
  '/chapters': typeof ChaptersIndexRoute
  '/missions': typeof MissionsIndexRoute
  '/people': typeof PeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/fund': typeof FundRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/me': typeof MeRoute
  '/partner': typeof PartnerRoute
  '/partner-room': typeof PartnerRoomRoute
  '/programs': typeof ProgramsRoute
  '/studio': typeof StudioRoute
  '/transparency': typeof TransparencyRoute
  '/trust': typeof TrustRoute
  '/verify': typeof VerifyRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/chapters/start': typeof ChaptersStartRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/people/$volunteerId': typeof PeopleVolunteerIdRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/fund'
    | '/impact'
    | '/join'
    | '/me'
    | '/partner'
    | '/partner-room'
    | '/programs'
    | '/studio'
    | '/transparency'
    | '/trust'
    | '/verify'
    | '/chapters/$chapterId'
    | '/chapters/start'
    | '/missions/$missionId'
    | '/partners/$partnerId'
    | '/people/$volunteerId'
    | '/chapters/'
    | '/missions/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/fund'
    | '/impact'
    | '/join'
    | '/me'
    | '/partner'
    | '/partner-room'
    | '/programs'
    | '/studio'
    | '/transparency'
    | '/trust'
    | '/verify'
    | '/chapters/$chapterId'
    | '/chapters/start'
    | '/missions/$missionId'
    | '/partners/$partnerId'
    | '/people/$volunteerId'
    | '/chapters'
    | '/missions'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/fund'
    | '/impact'
    | '/join'
    | '/me'
    | '/partner'
    | '/partner-room'
    | '/programs'
    | '/studio'
    | '/transparency'
    | '/trust'
    | '/verify'
    | '/chapters/$chapterId'
    | '/chapters/start'
    | '/missions/$missionId'
    | '/partners/$partnerId'
    | '/people/$volunteerId'
    | '/chapters/'
    | '/missions/'
    | '/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  FundRoute: typeof FundRoute
  ImpactRoute: typeof ImpactRoute
  JoinRoute: typeof JoinRoute
  MeRoute: typeof MeRoute
  PartnerRoute: typeof PartnerRoute
  PartnerRoomRoute: typeof PartnerRoomRoute
  ProgramsRoute: typeof ProgramsRoute
  StudioRoute: typeof StudioRoute
  TransparencyRoute: typeof TransparencyRoute
  TrustRoute: typeof TrustRoute
  VerifyRoute: typeof VerifyRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRoute
  ChaptersStartRoute: typeof ChaptersStartRoute
  MissionsMissionIdRoute: typeof MissionsMissionIdRoute
  PartnersPartnerIdRoute: typeof PartnersPartnerIdRoute
  PeopleVolunteerIdRoute: typeof PeopleVolunteerIdRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund': {
      id: '/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof FundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-room': {
      id: '/partner-room'
      path: '/partner-room'
      fullPath: '/partner-room'
      preLoaderRoute: typeof PartnerRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/start': {
      id: '/chapters/start'
      path: '/chapters/start'
      fullPath: '/chapters/start'
      preLoaderRoute: typeof ChaptersStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$missionId': {
      id: '/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof MissionsMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$partnerId': {
      id: '/partners/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof PartnersPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$volunteerId': {
      id: '/people/$volunteerId'
      path: '/people/$volunteerId'
      fullPath: '/people/$volunteerId'
      preLoaderRoute: typeof PeopleVolunteerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  FundRoute: FundRoute,
  ImpactRoute: ImpactRoute,
  JoinRoute: JoinRoute,
  MeRoute: MeRoute,
  PartnerRoute: PartnerRoute,
  PartnerRoomRoute: PartnerRoomRoute,
  ProgramsRoute: ProgramsRoute,
  StudioRoute: StudioRoute,
  TransparencyRoute: TransparencyRoute,
  TrustRoute: TrustRoute,
  VerifyRoute: VerifyRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRoute,
  ChaptersStartRoute: ChaptersStartRoute,
  MissionsMissionIdRoute: MissionsMissionIdRoute,
  PartnersPartnerIdRoute: PartnersPartnerIdRoute,
  PeopleVolunteerIdRoute: PeopleVolunteerIdRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
  MissionsIndexRoute: MissionsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
