#!/usr/bin/env node
/**
 * GOODNESS OS — local stack credentials.
 *
 * Mints everything docker/docker-compose.yml needs: a Postgres password, a JWT secret, and the
 * anon / service-role keys signed with it. These are development credentials for a stack that
 * listens on localhost only — they are generated per machine and never committed.
 *
 *   npm run stack:keys            # writes docker/.env if it does not exist
 *   npm run stack:keys -- --force # regenerate (invalidates any tokens already issued)
 *   npm run stack:keys -- --print # show the values without writing
 */
import { createHmac, randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const envPath = resolve(root, 'docker/.env')
const args = process.argv.slice(2)
const force = args.includes('--force')
const printOnly = args.includes('--print')

const b64url = (input) => Buffer.from(input).toString('base64url')

/** Minimal HS256 JWT — the same shape Supabase issues for its anon and service-role keys. */
function signJwt(payload, secret) {
  const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }))
  const body = b64url(JSON.stringify(payload))
  const signature = createHmac('sha256', secret).update(`${header}.${body}`).digest('base64url')
  return `${header}.${body}.${signature}`
}

function generate() {
  const issuedAt = Math.floor(Date.UTC(2026, 0, 1) / 1000)
  const expiresAt = issuedAt + 60 * 60 * 24 * 365 * 10
  const jwtSecret = randomBytes(32).toString('hex') // 64 chars, comfortably over the 32-byte floor
  const claims = (role) => ({ iss: 'supabase-goodness-local', role, iat: issuedAt, exp: expiresAt })
  return {
    POSTGRES_PASSWORD: randomBytes(18).toString('base64url'),
    JWT_SECRET: jwtSecret,
    ANON_KEY: signJwt(claims('anon'), jwtSecret),
    SERVICE_ROLE_KEY: signJwt(claims('service_role'), jwtSecret),
  }
}

const file = (values) => `# GOODNESS OS — local stack credentials. Generated by npm run stack:keys.
# Development only: this stack listens on localhost and these keys are unique to this machine.
# Never commit this file (docker/.gitignore keeps it out) and never reuse it for a hosted project.

POSTGRES_DB=postgres
POSTGRES_PASSWORD=${values.POSTGRES_PASSWORD}

JWT_SECRET=${values.JWT_SECRET}
JWT_EXPIRY=3600
ANON_KEY=${values.ANON_KEY}
SERVICE_ROLE_KEY=${values.SERVICE_ROLE_KEY}

# Where the app runs, and where magic links are allowed to return to.
SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=http://localhost:3000,http://localhost:3000/**
SUPABASE_PUBLIC_URL=http://localhost:54321

# Ports on the host. These match the Supabase CLI defaults on purpose.
API_PORT=54321
POSTGRES_PORT_EXTERNAL=54322
STUDIO_PORT=54323
MAIL_PORT=54324

# Set to false to bring the stack up with an empty schema instead of the seeded content.
APPLY_SEED=true

# Set to true to skip the emailed link entirely and sign in immediately (handy for e2e runs).
MAILER_AUTOCONFIRM=false

PGRST_DB_SCHEMAS=public
STUDIO_DEFAULT_ORGANIZATION=Goodness Society
STUDIO_DEFAULT_PROJECT=GOODNESS OS
`

const readExisting = () => {
  const text = readFileSync(envPath, 'utf8')
  const pick = (key) => new RegExp(`^${key}=(.*)$`, 'm').exec(text)?.[1] ?? ''
  return { ANON_KEY: pick('ANON_KEY'), SERVICE_ROLE_KEY: pick('SERVICE_ROLE_KEY'), POSTGRES_PASSWORD: pick('POSTGRES_PASSWORD') }
}

let values
if (existsSync(envPath) && !force && !printOnly) {
  values = readExisting()
  console.log('docker/.env already exists — keeping it. Use --force to regenerate.\n')
} else {
  values = generate()
  if (!printOnly) {
    writeFileSync(envPath, file(values))
    console.log(`wrote docker/.env\n`)
  }
}

console.log('Point the app at the local stack by putting these two lines in app/.env:\n')
console.log('VITE_SUPABASE_URL=http://localhost:54321')
console.log(`VITE_SUPABASE_ANON_KEY=${values.ANON_KEY}\n`)
console.log('Service-role key (server-side only, never ship it to a browser):')
console.log(`${values.SERVICE_ROLE_KEY}\n`)
console.log('Then: docker compose -f docker/docker-compose.yml up -d')
