import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * Page copy contract.
 *
 * Each rebuilt page must still carry the copy its design file defines — the lines that make the
 * product's promises, not just decoration. Extended one page at a time as pages are rebuilt from
 * their `.dc.html` source.
 */
const root = resolve(__dirname, '../../..')

/**
 * The design files carry the same words in three encodings: literal characters in markup, numeric
 * HTML entities, and JavaScript `\uXXXX` escapes inside the logic blocks. Normalise all three so a
 * comparison is about words, not encoding.
 */
const normalise = (text: string) =>
  text
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, hex: string) =>
      String.fromCharCode(parseInt(hex, 16)),
    )
    .replace(/&#(\d+);/g, (_, code: string) =>
      String.fromCharCode(Number(code)),
    )
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/&quot;/g, '"')
    .replace(/[’‘]/g, "'")
    .replace(/\s+/g, ' ')
    .trim()

interface PageContract {
  page: string
  design: string
  routes: Array<string>
  /** Copy that must survive from the design into the build. */
  copy: Array<string>
}

const CONTRACTS: Array<PageContract> = [
  {
    page: 'Missions board',
    design: 'Missions.dc.html',
    routes: ['missions/index.tsx', '../components/MissionCard.tsx'],
    copy: [
      'Live Now',
      'Do one',
      'meaningful thing',
      "You don't have to join an organisation to make a difference today",
      'Become a volunteer',
      'My missions',
      'Open missions',
      'Positions to fill',
      'Chapters active',
      'Volunteer hours open to claim',
      'Search missions, venue, role…',
      'All missions',
      'Open now',
      'Urgent',
      'Remote',
      'No missions match that',
      'Try another search or clear the filters.',
      'positions filled',
      'service hours',
      'View mission',
      'View report',
    ],
  },
  {
    page: 'Mission detail',
    design: 'Mission Detail.dc.html',
    routes: ['missions/$missionId.tsx'],
    copy: [
      'All missions',
      'Share this mission',
      'Chapter',
      'When',
      'Where',
      'Service hours',
      'Added on verification',
      'Mission lead',
      'Roles needed',
      'filled',
      'positions',
      'Helpful skills:',
      'Open to everyone — no specific skills needed',
      'Claim role',
      'Change to this',
      'Your role',
      'Impact report',
      'people supported · published record',
      'Delivered',
      'What changed',
      'See the full impact record',
      'Impact target',
      'Team joined',
      'No one from the platform has claimed a role yet. Be the first.',
      'Your place on this mission',
      'Sign in to My Goodness to claim a role.',
      'Sign in to join',
      'Pick a role on the left to join this mission.',
      "You're on this mission",
      'Check-in code',
      'Show this to your mission lead on the day, or tap below.',
      'Remote contribution',
      "No check-in needed. Start when you're ready, then submit your completion for verification.",
      'Start contribution',
      'Check in now',
      'Submit completion',
      'Your contribution has been submitted for verification.',
      'Hours verified',
      'Leave mission',
      'Leave this mission?',
      'Your position becomes available to another volunteer straight away.',
      'Yes, leave',
      'Keep my place',
      'How it works',
      'Contribution submitted',
      'Your team lead confirms — hours post to your passport.',
    ],
  },
  {
    page: 'Impact',
    design: 'Impact.dc.html',
    routes: ['impact.tsx'],
    copy: [
      "We don't stop at what we delivered.",
      'We measure what changed.',
      'people supported through published impact records. Counted once per record',
      'someone who joins two programmes appears in both records.',
      'Outputs',
      'What we delivered — sessions run, people trained, packs distributed.',
      'Outcomes',
      'What changed because of it — jobs secured, accounts opened, commitments won.',
      'Published records',
      'Fully verified evidence',
      'Output targets met',
      'Outcomes awaiting measurement',
      'Where the work happened',
      'Break it down by',
      'program',
      'Click a program to see the records, targets, outcomes, and the evidence behind each claim.',
      'All published records',
      'Show all programs',
      'published records',
      'Published',
      'Outputs · what we delivered',
      'targets met',
      'No numeric targets set',
      'Outcomes · what changed',
      'Each claim shows how we know it.',
      'Source: ',
      'Evidence',
      'items verified by our team',
      'Verified',
      'Pending',
      'Self-reported',
      'Observed',
      'Awaiting measurement',
      'Evidence verified',
      'Evidence pending',
      'How to read this',
      'Confirmed against a document or third-party record.',
      'Told to us by participants, usually via survey.',
      'Recorded by our team in the field.',
      'Too early to know. We publish the date, not a guess.',
      'Draft records stay internal until published. Publishing a record does not verify it',
      'This is what goodness looks like',
      'when we organize it.',
      'Every number on this page traces back to a mission, a verified volunteer, and a document you can ask to see.',
      'Join a mission',
      'Fund this work',
    ],
  },
  {
    page: 'Trust Ledger',
    design: 'Trust Ledger.dc.html',
    routes: ['trust.tsx'],
    copy: [
      'Trust Ledger · 2026 year to date',
      'Follow every taka',
      'from the donation to the outcome.',
      'Received',
      'recorded donations',
      'Allocated to funds',
      'not yet allocated',
      'budgeted',
      'Accepted into the ledger',
      'recorded, awaiting review',
      'Programme spending',
      'Operations & administration',
      'of accepted spending',
      'of accepted spending has a document attached',
      'fully checked by our team',
      'Figures cover 1 Jan – 31 Aug 2026.',
      'These are our own books, reviewed internally and audited annually.',
      'Step 1 · Allocation',
      'Where the money',
      'is committed',
      'Click a fund to see its budget, every expense against it, the documents behind each one, and the impact record it supported.',
      'accepted',
      'budget',
      'with documents',
      'funding gap',
      'Step 2 · Spending',
      'received as restricted gifts',
      'restricted balance remaining',
      'Funded from unrestricted giving',
      'Budget exceeds allocated funds by',
      'this programme is still seeking funding.',
      'Allocated',
      'Accepted spending',
      'Unspent allocation',
      'Funding gap',
      'Close',
      'Expense',
      'Amount',
      'Payee & date',
      'Documents',
      'Ledger status',
      'Supported:',
      'checked',
      'attached',
      'No document yet',
      'Awaiting review',
      'Step 3 · This spending supported',
      'documents verified',
      'Full record',
      'This fund supported the work above; the recorded impact is not a conversion of taka into outcomes.',
      'Pick a fund above to follow the money through to the work it paid for.',
      'Money in',
      'Every donation',
      'we have recorded',
      'Donor',
      'Date',
      'Restricted to',
      'Receipt issued',
      'Unrestricted',
      'Individual donors are listed by the name they gave us; anyone may ask to appear as an anonymous donor',
      'Restricted gifts can only be spent on the programme named.',
      'Fund a mission and',
      'watch it move through this page.',
      'Your gift is recorded here, allocated to a fund, spent against documented invoices, and tied to the impact record it supported.',
      'Fund this work',
      'See the impact',
    ],
  },
  {
    page: 'Chapters',
    design: 'Chapters.dc.html',
    routes: ['chapters/index.tsx'],
    copy: [
      'The Network',
      'One organisation.',
      'Goodness, everywhere.',
      'Chapters run their own missions with their own leaders',
      'Every number below is computed from the same records as the rest of the platform.',
      'Start a chapter in your city',
      'Active chapters',
      'Forming chapters',
      'Chapter members',
      'Verified hours across the network',
      'Across Goodness right now',
      'is forming — leadership team assembling',
      'more volunteers',
      'published —',
      'people supported',
      'District chapter',
      'University chapter',
      'Forming',
      'under',
      'Members',
      'Missions live',
      'People supported',
      'Partners',
      'Leadership team being established · Goodness standards',
      'Leadership forming',
      'Visit chapter',
      'Follow progress',
      "Don't see Goodness in your city?",
      'Start a chapter.',
      'Chapters begin with a few committed people.',
      'City or campus *',
      'Your name & contact *',
      'Why here? Local needs, your team, your Goodness ID if you have one',
      'Propose the chapter',
      'City and contact are required.',
      'Lifecycle: Proposed → Forming (leadership + Goodness standards) → Active.',
      'Chapter proposal received — HQ reviews it and, if approved, your chapter appears here as Forming. Watch this page.',
    ],
  },
  {
    page: 'Chapter',
    design: 'Chapter.dc.html',
    routes: ['chapters/$chapterId.tsx'],
    copy: [
      '← All chapters',
      'District chapter',
      'University chapter',
      'Forming',
      'under',
      'Members',
      'Verified hours',
      'People supported',
      'Local partners',
      'Deployed locally',
      'Goodness standards',
      'supported by',
      'Needed now',
      'How you can help this chapter this week.',
      'Local partner',
      'Fund or resource',
      'next initiative',
      'Missions in',
      'No missions listed here yet.',
      'Published impact from this chapter',
      "No published impact records yet — nothing is invented before it's measured.",
      'From this chapter',
      'Chapter team',
      'Leadership team being established.',
      'Lead? Chapter Control',
      '2026 goals',
      'Partners powering',
      'No local partners yet — be the first.',
      'Help fund',
      'This is your chapter',
      'Make this my chapter',
      'Help form this chapter',
      'Your primary chapter is where you belong organisationally — you can still join missions anywhere in Goodness.',
      'SHARE THIS CHAPTER:',
      'Proud member',
      'Chapter milestone',
      'Year in review',
      'Recruit founding volunteers',
    ],
  },
  {
    page: 'Our Volunteers',
    design: 'Volunteers.dc.html',
    routes: ['people/index.tsx'],
    copy: [
      'Our Volunteers',
      'Meet our',
      'Change-Makers',
      "Every person here chose to show up. They bring their time, skills, and belief that things can be better — and together, they're proving it.",
      'Get Listed Here',
      'Active Volunteers',
      'Cities Represented',
      'Programs Supported',
      'Verified Service Hours',
      'Featured',
      'View profile',
      'Search by name, skill or city…',
      'volunteer',
      'matching',
      'No volunteers found',
      'Try a different search or filter.',
      'Since',
      'change-makers and counting',
      'Your name',
      'belongs here.',
      'Join a community of professionals, students, and community leaders using their skills to create real, lasting change.',
      'Apply to Volunteer',
      'See Our Programs',
    ],
  },
  {
    page: 'Goodness Passport',
    design: 'Volunteer Profile.dc.html',
    routes: ['people/$volunteerId.tsx'],
    copy: [
      '← All volunteers',
      '✓ Verified',
      'Sustaining Member ✓',
      'since',
      'Goodness Passport',
      'Missions',
      'Verified service hours',
      'Programs',
      'About',
      'Skills',
      'Downloads',
      'Official branded assets for',
      '— issued and controlled by Goodness Society.',
      'Certificate of Volunteer Service',
      'issued & enabled by admin',
      'Open & download',
      'Not yet issued — becomes available once enabled by the admin team',
      'Locked',
      'Share this moment',
      'Cards pre-filled from live verified records — numbers locked, never typed',
      'Open Share Studio',
      'QUICK CARDS:',
      'My identity',
      'Hour milestone',
      'Mission milestone',
      'Credential',
      'My Year in Goodness',
      'Journey',
      'Current level',
      'Completed',
      'Next step',
      'Credentials',
      'Valid',
      'Revoked',
      'Volunteer like',
      'National network',
      'Since',
    ],
  },
  {
    page: 'My Goodness',
    design: 'My Goodness.dc.html',
    routes: [
      'me.tsx',
      '../components/CommitmentPanel.tsx',
      '../components/IdentityPicker.tsx',
    ],
    copy: [
      'My',
      'Goodness',
      'Your verified service, credentials, and shareable assets in one place. Choose your Goodness Passport to sign in.',
      'Sign in as',
      'Search your name…',
      'Sign in',
      'Sign out',
      "You've contributed",
      'of verified service across',
      'Missions',
      'Verified hours',
      'Credentials',
      'Current level',
      'My missions',
      'Find a mission',
      'Hours post to your passport the moment your team lead verifies them.',
      "You haven't joined a mission yet",
      'Pick one meaningful thing to do this week — roles start at 4 hours.',
      'Browse missions',
      'Recommended for you',
      'Matches your',
      'In your program —',
      'Close to you in',
      'Remote — fits any schedule',
      'View',
      'Hours verified',
      'Submitted',
      'In progress',
      'Checked in',
      'Joined',
      'My assets',
      'Issued by Goodness Society. Locked items unlock when the team enables them.',
      'My certificate of service',
      'Ref',
      'Download',
      'Awaiting issue by the Goodness team',
      'Locked',
      'My social card',
      'Pre-filled with your profile · 1080×1080 PNG',
      'Create',
      'My credentials',
      'No credentials yet. Complete missions and your first credential will appear here.',
      'Valid',
      'Revoked',
      'Verify ↗',
      'Next milestone',
      'hours of service',
      'hours ·',
      'to go',
      'My journey',
      'Current level',
      'Completed',
      'Next step',
      'My chapter',
      'All chapters',
      'Near you',
      'spots',
      'Make a different chapter your home:',
      'Your primary chapter is where you belong organisationally — you can join missions anywhere in Goodness.',
      'Goodness Commitment',
      'Contribute what you can, when you can — Goodness appreciates the commitment, not the size.',
      'Amount',
      'Rhythm',
      'Goes to',
      'Wherever Goodness needs it most',
      'My Chapter',
      'Start my commitment',
      'Entirely voluntary — never a membership fee. Time, skills, and leadership count just as much.',
      "You're sustaining Goodness",
      'Commitment paused',
      'Supporting:',
      'sustaining since',
      'Contribute now',
      'contributed',
      'Thank you for helping keep Goodness moving.',
      "Commitment paused — everything you've contributed remains part of your Goodness history. Resume whenever you're ready.",
      'Pause commitment',
      'Resume commitment',
      'Change amount or rhythm',
      'Show Sustaining Member on my Passport',
      'SHARE THIS MOMENT:',
      'Sustaining Member',
      'Commitment milestone',
      'Impact I backed',
      'My Year',
      'Change or pause any time — your recognition never downgrades. Every contribution enters the Trust Ledger with a receipt.',
      'Trace my contributions',
      'sustaining Goodness with active commitments.',
      'Small commitments. One strong movement.',
      'My giving',
      'You support Goodness with money as well as time.',
      'receipts issued for every gift',
      'a shared result, not a private conversion of your taka.',
      'See your gifts on the Trust Ledger',
      'Back another initiative',
      'View my public passport',
    ],
  },
  {
    page: 'Fund Impact',
    design: 'Fund Impact.dc.html',
    routes: ['fund.tsx'],
    copy: [
      'Fund Impact',
      "Don't just donate.",
      'Back measurable impact.',
      'Every opportunity below has a funding target, expected outcomes, and a public trail — your contribution joins its funding pool, the work is delivered by verified volunteers, and the results land on the Impact page and Trust Ledger with evidence.',
      'See where money goes',
      'Partner Room',
      'Open now',
      'initiatives',
      'seeking funding',
      'still needed across all open initiatives',
      'Urgent',
      'secured of',
      'still seeking partners',
      'funded',
      'Expected outcomes · measured & published',
      'Fund this initiative',
      'Past results',
      'Your contribution joins the funding pool supporting an initiative',
      'we never claim a fixed',
      '-per-life conversion',
      'What the initiative collectively achieves is reported on the Impact page with outputs, outcomes, and evidence, and every taka is traceable on the Trust Ledger.',
      'Secured',
      'means signed commitments; cash actually received is what the Trust Ledger reports — the two are never blurred.',
      'Already a partner?',
      'Your Partner Room is live.',
      'A live window into your partnership — funding deployed, missions underway, the people delivering the work, and the evidence behind every claim.',
      'Open Partner Room',
    ],
  },
  {
    page: 'Partner with Us',
    design: 'Partner.dc.html',
    routes: ['partner.tsx'],
    copy: [
      'Partner with Us',
      'Build the future',
      'with us',
      'Together, we can create meaningful, measurable, and sustainable change. Whether you bring funding, expertise, or network — your involvement matters.',
      'Live funding opportunities',
      'Build',
      'measurable impact with us',
      'All opportunities',
      'Urgent',
      'still needed',
      'funded',
      'Partnership builder',
      'Tell us what matters —',
      "we'll match the opportunity.",
      'What matters to you',
      'Any cause',
      'Where',
      'You bring',
      'Funding',
      'Employee skills & time',
      'Technology / venue / in-kind',
      'Several of these',
      'opportunities fit your goals',
      'Matches your cause',
      'Open to all causes',
      'employee volunteering welcome',
      'in-kind contributions listed',
      'needed',
      'Express interest — start this partnership',
      'Organisation name *',
      'Contact person & email *',
      'Approximate commitment…',
      'In-kind / mixed',
      'Your objective (optional)',
      'Start this partnership',
      'Organisation and contact are required.',
      'Partnership request received — our partnerships team will reach out within 48 hours. It is already in our pipeline.',
      'Our partners',
      'Every partner name opens a live page of what the partnership supports and what happened — a logo here is a gateway to evidence.',
      'Who We Collaborate With',
      'Five ways to',
      'get involved',
      'Corporate Partners',
      'CSR alignment, employee volunteering, and co-branded impact programs. We help companies make social investment measurable.',
      'Branded impact report + Employee engagement program',
      'Foundations & Grantors',
      'Quarterly grant reports + Independent evaluation',
      'Educational Institutions',
      'Co-branded curriculum + Student placement pathways',
      'Technology Companies',
      'beneficiaries + Impact showcase',
      'Individual Donors',
      'Personal impact dashboard + Donor newsletter',
      'The Process',
      'What happens',
      'next',
      'Submit your enquiry',
      'Fill in the form below with your organisation and partnership interests.',
      'Discovery call',
      'Our partnerships team will reach out within 48 hours for a 30-minute alignment call.',
      'Partnership proposal',
      'We draft a tailored proposal with scope, reporting cadence, and expected outcomes.',
      'Get in Touch',
      'Send us an enquiry',
      'Full Name *',
      'Organisation',
      'Email Address *',
      'Partnership Type *',
      'Select a type...',
      'Corporate Partner',
      'Foundation / Grantor',
      'Educational Institution',
      'Technology Company',
      'Individual Donor',
      'Message *',
      'Please fill in all required fields (*) before sending.',
      'Send Enquiry',
      "We'll respond within 48 hours — hello@goodnesssociety.org",
      'Thank you!',
      "We've received your enquiry and will be in touch within 48 hours for a discovery call.",
    ],
  },
  {
    page: 'Partner Room',
    design: 'Partner Room.dc.html',
    routes: ['partner-room.tsx'],
    copy: [
      'Partner',
      'Room',
      'A live window into your partnership — not a quarterly PDF. Choose your organisation to enter.',
      'Sign in as',
      'since',
      'Enter',
      'Public profile ↗',
      'Sign out',
      'Partnership since',
      'Your partnership is creating measurable progress.',
      'Committed',
      'Received',
      'Programme spending to date (shared across funders)',
      'People supported through initiatives you back (shared)',
      'Happening now',
      'Live missions in the programmes your funding supports.',
      'No missions live this week — the next cohort is being scheduled.',
      'roles filled',
      'Your funding supports this',
      'Trace our contribution',
      'received',
      'committed · receipts issued',
      'allocated',
      'programme fund',
      'your gift joins',
      'accepted expenses',
      'deployed',
      'documents checked',
      'published impact records',
      'for the programmes you support',
      'people supported',
      'collectively, across those programmes',
      'verified',
      'self-reported',
      'observed',
      'awaiting measurement — we publish dates, not guesses',
      'Trust Ledger',
      'Impact records',
      'Partnership timeline',
      'Our commitments',
      'What we agreed to do together, and where we are.',
      'Goodness Society',
      'Partnership goal',
      'to go',
      'People delivering the work',
      'Verified volunteers in your programmes.',
      'verified hours',
      'Employee volunteering',
      'Employees',
      'Service hours',
      'Sessions',
      'Open missions your team can join',
      'In-kind contribution',
      'None recorded for this partnership.',
      'est.',
      'Reports & sharing',
      'Quarterly impact brief',
      'Shareable live partnership page',
      'Create impact milestone card',
      'SHARE STUDIO — PRE-FILLED FOR THIS PARTNERSHIP',
      'Announcement',
      'Impact milestone',
      'Employee hours',
      'Anniversary',
      'Our Year in Goodness',
      'Where we can go next',
      'funding gap',
      'Your partnership has watched this grow all year. The natural next chapter is already scoped on the Fund Impact board.',
      'See the opportunity',
      'Programme figures are pooled: your funding joins other gifts supporting the same programmes, so',
      'reflects what those programmes achieved collectively — not a private conversion of your taka into outcomes.',
    ],
  },
  {
    page: 'Partner Profile',
    design: 'Partner Profile.dc.html',
    routes: ['partners/$partnerId.tsx'],
    copy: [
      '× Goodness Society',
      'since',
      'Published impact records',
      'People supported by those programmes',
      'Employee volunteering',
      'Partner-only',
      'Funding details are shared privately',
      'Committed',
      'In-kind',
      'Non-cash partnership',
      'Partnering for verified impact.',
      "Every figure on this page is live from Goodness Society's own records — the same numbers shown on the public Impact page and Trust Ledger. Programme results are collective, supported by this partnership alongside other funding and volunteer effort.",
      'Programmes supported',
      'published record',
      'published records',
      'people supported',
      'What those programmes have published',
      'awaiting measurement',
      'Outcomes not yet recorded',
      'Record',
      'Follow the money',
      'Partner with Goodness',
    ],
  },
  {
    page: 'Verify',
    design: 'Verify.dc.html',
    routes: ['verify.tsx'],
    copy: [
      'Credential',
      'verification',
      'Every certificate issued by Goodness Society carries a reference number. Enter it below — or scan the QR code on the document — to confirm it is genuine.',
      'e.g. GS-VOL-2024-0100',
      'Verify',
      'Credential Verified',
      'Goodness Society',
      'Issued to',
      'Program',
      'Verified service',
      'hours ·',
      'missions',
      'Issued',
      'Status',
      'Valid',
      'View public Goodness Passport',
      'Credential Revoked',
      'This reference was issued to',
      'but has since been revoked by Goodness Society and is no longer valid. Contact',
      'hello@goodnesssociety.org',
      'if you believe this is an error.',
      'No credential found',
      'We could not find a credential with that reference. Check the number on the document and try again.',
      'Try a live reference',
    ],
  },
  {
    page: 'Volunteer with Us',
    design: 'Volunteer.dc.html',
    routes: ['join.tsx'],
    copy: [
      'Volunteer with Us',
      'Give your time.',
      'Change a life.',
      "Whether you're a professional, student, or community member — your skills and time can drive real change for the people in our programs.",
      'Active Volunteers',
      'Programs to Support',
      'Why Volunteers Love Us',
      'What you gain',
      'Make Real Impact',
      'Your skills directly support people building better futures for themselves.',
      'Grow Your Network',
      'Connect with professionals, community leaders, and change-makers across sectors.',
      'Develop Skills',
      'Gain facilitation, project management, and social impact experience.',
      'Verified Reference',
      'Receive an official volunteer reference letter from Goodness Society.',
      'Open Roles',
      'Find your',
      'place',
      'Preparing for modern careers',
      'Future-proofing the workforce',
      'Unlocking the next generation',
      'Grassroots change at scale',
      'Technology as a change agent',
      'Active',
      'The Process',
      'How to join',
      'Submit application',
      'Fill in the form below with your background and area of interest.',
      'Screening call',
      'A 20-minute call with our volunteer coordinator to align on fit and expectations.',
      'Onboarding session',
      'Join a virtual or in-person orientation to meet the team and understand your role.',
      'Start volunteering',
      'Begin contributing — your impact starts from day one.',
      'Apply Now',
      'Volunteer application',
      'Application received!',
      'Thank you for applying. Our volunteer coordinator will reach out within 3–5 business days to schedule a screening call. Once approved, your Goodness Passport goes live.',
      'Go to My Goodness',
      'First Name *',
      'Last Name *',
      'Email Address *',
      'Phone Number',
      'City / Location *',
      'Program of Interest *',
      'Select a program...',
      'Volunteer Role',
      'Select a program first',
      'Select a role...',
      'Availability *',
      'Select availability...',
      'Weekdays (daytime)',
      'Weekday evenings',
      'Weekends only',
      'Flexible / As needed',
      'Full-time commitment (3+ months)',
      'Relevant Experience / Background',
      'e.g. Software engineer with 5 years experience, Teacher, HR Professional...',
      'Why do you want to volunteer? *',
      "Tell us what drives you to contribute to Goodness Society's mission...",
      'Please fill in all required fields (*) before submitting.',
      'Submit Application',
      'Questions? Email us at',
      'volunteers@goodnesssociety.org',
    ],
  },
  {
    page: 'About Us',
    design: 'About.dc.html',
    routes: ['about.tsx'],
    copy: [
      'About Us',
      'Who we',
      'are',
      'Goodness Society is a government-registered, non-profit organisation dedicated to creating sustainable social impact through education, skills development, technology, and community empowerment.',
      'We believe that',
      'meaningful change happens',
      'when good intentions are combined with',
      'transparency, accountability, and measurable results.',
      'Our Vision',
      'To create a society where every individual has access to',
      'opportunities that enable them to thrive,',
      'contribute, and succeed in an evolving world.',
      'Our Mission',
      'To design and execute impactful initiatives that improve lives through',
      'education, workforce readiness, technology adoption,',
      'and community development.',
      'Our Edge',
      'What makes',
      'us different',
      'Radical Transparency',
      'Every donation, project expense, milestone, and impact report is openly documented and shared with our donors and community.',
      'Measurable Impact',
      'We focus on outcomes, not activities. Every initiative has clear goals, success metrics, and public reporting built in.',
      'Sustainable Change',
      'Rather than temporary assistance, we invest in programs that create long-term opportunities and self-sufficiency.',
      'Technology-Driven Accountability',
      'We leverage digital tools, dashboards, and public reporting systems to ensure every contribution can be tracked and verified.',
      'The People',
      'Our team',
    ],
  },
  {
    page: 'Our Programs',
    design: 'Programs.dc.html',
    routes: ['programs.tsx'],
    copy: [
      'Our Programs',
      'pathways to',
      'lasting change',
      'Every program is designed with measurable goals, community input, and public accountability. We build for outcomes — not outputs.',
      'Active',
      'Participants',
      'Partners',
      'Preparing for modern careers',
      'We prepare students and young professionals for modern careers through practical training, industry mentorship, and real-world project exposure.',
      'Future-proofing the workforce',
      'Helping individuals adapt to the future of work through AI literacy, automation training, and technology-focused learning programs.',
      'Unlocking the next generation',
      'Supporting young people aged 16–30 with skills, resources, mentorship networks, and opportunities that unlock their potential.',
      'Grassroots change at scale',
      'Launching initiatives that address local challenges and improve quality of life through collaborative, community-led action.',
      'Technology as a change agent',
      'Exploring and deploying technology-driven solutions that create scalable and lasting social impact.',
      'Volunteer for this program',
      'Program Goals',
      'Train 500+ students annually in career-ready skills',
      'Partner with 15+ companies for internship placements',
      'Achieve 80%+ employment rate within 6 months of graduation',
      'Deliver CV writing, interview prep, and portfolio building',
      'Deliver AI literacy to 1,000 individuals annually',
      'Train 200 professionals in automation and no-code tools',
      'Build a community of AI-enabled graduates in the region',
      'Partner with tech companies for live tooling access',
      'Reach 800 young people through skills bootcamps',
      'Establish mentorship circles in 5 cities',
      'Award 50 micro-grants to youth-led initiatives annually',
      'Build a youth alumni network of 2,000+ members',
      'Launch 3 community development projects per year',
      'Engage 50+ community leaders and stakeholders',
      'Deliver infrastructure and resource support to underserved areas',
      'Track and publish community well-being metrics annually',
      'Launch 2 social-good tech products per cycle',
      'Open-source all non-proprietary tools and methodologies',
      'Partner with universities for research and co-development',
      'Create an innovation grant fund for social entrepreneurs',
      'Support a program that',
      'changes lives',
      'Partner with us to fund, sponsor, or co-design a program initiative.',
      'Partner with Us',
      'Volunteer with Us',
    ],
  },
  {
    page: 'Transparency',
    design: 'Transparency.dc.html',
    routes: ['transparency.tsx'],
    copy: [
      'Our Open Books',
      'Nothing to hide.',
      'Everything to show.',
      'We publish every financial figure, every impact metric, and every milestone. This page is our commitment to accountability — updated quarterly.',
      'Total Raised (2024, audited)',
      'Across 2 funding rounds',
      'Total Spent (2024, audited)',
      '89% utilisation rate',
      'Overhead Ratio (2024, audited)',
      'Below 15% benchmark',
      'People Supported',
      'Backed by published impact records',
      'Fund Allocation',
      'Where your money goes',
      'Programs & Activities',
      'Operations & Staff',
      'Administration',
      'Programs',
      'Quarterly Finances',
      'Raised vs Spent',
      'Raised',
      'Spent',
      'Cumulative Impact',
      'People Supported (2024)',
      '180 in January',
      'in published records',
      'Track Record',
      'Our',
      'milestones',
      'Organisation officially registered',
      'First education cohort launched — 45 participants',
      'raised in first funding round',
      'AI & Digital Skills program launched in partnership with TechHub Dhaka',
      '500th beneficiary milestone reached',
      'Second funding round',
      'Youth Empowerment bootcamp — 120 graduates',
      'First annual report published — audited accounts and programme results',
      'Our Pledge',
      'donor commitments',
      'Open Books',
      'All financial records are available for public review on request.',
      'Impact Reports',
      'Quarterly reports published showing program outcomes and metrics.',
      'Donor Protection',
      'Your contributions are ring-fenced and allocated only to stated programs.',
      'Audit Compliance',
      'Annual independent audit conducted and results publicly disclosed.',
      'Progress Tracking',
      'Every initiative has a public milestone tracker updated monthly.',
      'Download our Annual Report',
      'These are the audited 2024 figures. For',
      'year-to-date, line by line, see the',
      'Trust Ledger',
      'its overhead share differs because the year is still in progress.',
      'Full 2024 Annual Impact Report — financials, outcomes, and forward outlook.',
      'Request PDF Report',
    ],
  },
  {
    page: 'Share Studio',
    design: 'Share Studio.dc.html',
    routes: ['studio.tsx', '../components/ShareCard.tsx', '../lib/cards.ts'],
    copy: [
      'GOODNESS SHARE STUDIO',
      'Every meaningful contribution becomes a shareable story.',
      'Cards are generated from your verified Goodness record. The numbers are locked — a Goodness share card is a social claim backed by the platform.',
      'Verified numbers locked',
      'Goodness Verified ✓ mark',
      'Square · Story · A4 poster',
      'Who are you?',
      'Sign in to generate cards from your own verified record.',
      'Switch',
      'For you',
      'My journey',
      'Giving',
      'Chapter',
      'Impact',
      'Missions & funding',
      'Partners',
      'Digests',
      'RECOMMENDED FOR YOU',
      'Create',
      'MY JOURNEY',
      'MEMBER & GIVING',
      'Amounts never appear on these cards — the commitment is what counts.',
      'MY CHAPTER & NETWORK',
      'Chapter pride, leadership, launches and national milestones — all counted live from the network.',
      'IMPACT & TRUST',
      'What happened afterward — published records, verified outcomes, and where the money went.',
      'MISSIONS & FUNDING',
      'Recruitment posters and funding cards, generated from live OS data — each type has its own look. Recruitment and funding support the A4 poster format for print.',
      'PARTNERS',
      'Partnership announcements, shared-impact milestones, employee volunteering and anniversaries — figures pull live from the Partner Room.',
      'WEEKLY & MONTHLY DIGESTS',
      'Recurring recap posts the OS writes itself — nobody hand-counts numbers on a Friday.',
      'SELECTED',
      'READY',
      'LOCKED',
      'URGENT',
      'Square 1080',
      'Story 1080×1920',
      'A4 poster',
      'GOODNESS VERIFIED ✓',
      'Goodness',
      'Society',
      'PERSONAL NOTE (OPTIONAL — THE ONLY EDITABLE FIELD ON THE CARD)',
      "e.g. Grateful to everyone I've worked alongside.",
      'SUGGESTED CAPTION',
      "Verified numbers on the card can't be edited — they come straight from your Goodness record. The caption is yours.",
      'FULLY FUNDED',
      'Together, we funded',
    ],
  },
  {
    page: 'Mission Control',
    design: 'Mission Control.dc.html',
    routes: ['admin.tsx', '../components/admin/AdminCommand.tsx'],
    copy: [
      'Mission Control',
      'Goodness OS',
      'Command',
      'Overview',
      'People',
      'Volunteers',
      'Applications',
      'Operations',
      'Missions',
      'Attendance',
      'Impact',
      'Finance',
      'Money & approvals',
      'Public Trust Ledger',
      'Growth',
      'Partners',
      'Network',
      'Trust',
      'Verify a credential',
      'Audit Log',
      'Live',
      'Admin',
      "What's happening in Goodness right now",
      'One view across people, operations, money, impact, partners, and the network · updates as you act',
      'View public site',
      'Active volunteers',
      'Live missions',
      'Hours to verify',
      'Verified hours',
      'People supported',
      'Accepted spending',
      'Decision inbox',
      'Everything across the OS waiting on HQ — one queue, newest first. Acting on an item happens in its domain; this inbox takes you straight there.',
      'Inbox zero — nothing in Goodness is waiting on HQ right now.',
      'Review',
      'Worth sharing now',
      'Moments across the OS that deserve a post — one click opens Share Studio with the card pre-selected, numbers already live.',
      'Create card',
      'Live operations by city',
      'Audit log',
      'No admin actions yet. Every change you make is recorded here — nothing is silently rewritten.',
    ],
  },
  {
    page: 'Chapter Control',
    design: 'Chapter Control.dc.html',
    routes: ['chapter-control.tsx'],
    copy: [
      'Chapter Control',
      'Goodness OS · local command',
      'Public network ↗',
      'HQ Mission Control ↗',
      'Run your chapter',
      'from one place.',
      'Sign in as a chapter lead. You operate locally; HQ approves the sensitive parts — autonomy within guardrails.',
      'Enter',
      'Members',
      'Missions live',
      'People supported',
      'Deployed locally',
      'Sign out',
      'From HQ',
      'Within your authority',
      'No HQ approval needed',
      'Low-risk local missions publish straight to the public board.',
      'Mission title, e.g. Weekend CV clinic',
      'Date, e.g. Sat 19 Sep 2026',
      'Roles: Mentor x4, Desk x2',
      'Publish local mission',
      'Title and date required.',
      "Published — it's live on the mission board.",
      'Needs HQ approval',
      'Guardrail',
      'Budgets, funding opportunities, and public impact records go to HQ first.',
      'Funding need (goes to Fund Impact if approved)',
      'Budget request',
      'Publish an impact record',
      'Amount if money, e.g. 320000',
      'Send to HQ for approval',
      'Title required.',
      'Attendance to verify · your missions',
      'Nothing awaiting verification in',
      'Verify',
      'Goodness standards',
      'Your team & members',
    ],
  },
]
describe.each(CONTRACTS)('$page follows $design', (contract) => {
  const design = normalise(readFileSync(resolve(root, contract.design), 'utf8'))
  const built = normalise(
    contract.routes
      .map((file) => readFileSync(resolve(__dirname, file), 'utf8'))
      .join('\n'),
  )

  it('quotes copy that really is in the design file', () => {
    for (const line of contract.copy) {
      expect(design, `"${line}" is not in ${contract.design}`).toContain(
        normalise(line),
      )
    }
  })

  it('keeps that copy in the build', () => {
    for (const line of contract.copy) {
      expect(built, `"${line}" is missing from the page`).toContain(
        normalise(line),
      )
    }
  })
})
