import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * Page copy contract.
 *
 * Each rebuilt page must still carry the copy its design file defines — the lines that make the
 * product's promises, not just decoration. Extended one page at a time as pages are rebuilt from
 * their `.dc.html` source.
 */
const root = resolve(__dirname, '../../..')

/**
 * The design files carry the same words in three encodings: literal characters in markup, numeric
 * HTML entities, and JavaScript `\uXXXX` escapes inside the logic blocks. Normalise all three so a
 * comparison is about words, not encoding.
 */
const normalise = (text: string) =>
  text
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, hex: string) =>
      String.fromCharCode(parseInt(hex, 16)),
    )
    .replace(/&#(\d+);/g, (_, code: string) =>
      String.fromCharCode(Number(code)),
    )
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/&quot;/g, '"')
    .replace(/[’‘]/g, "'")
    .replace(/\s+/g, ' ')
    .trim()

interface PageContract {
  page: string
  design: string
  routes: Array<string>
  /** Copy that must survive from the design into the build. */
  copy: Array<string>
}

const CONTRACTS: Array<PageContract> = [
  {
    page: 'Missions board',
    design: 'Missions.dc.html',
    routes: ['missions/index.tsx', '../components/MissionCard.tsx'],
    copy: [
      'Live Now',
      'Do one',
      'meaningful thing',
      "You don't have to join an organisation to make a difference today",
      'Become a volunteer',
      'My missions',
      'Open missions',
      'Positions to fill',
      'Chapters active',
      'Volunteer hours open to claim',
      'Search missions, venue, role…',
      'All missions',
      'Open now',
      'Urgent',
      'Remote',
      'No missions match that',
      'Try another search or clear the filters.',
      'positions filled',
      'service hours',
      'View mission',
      'View report',
    ],
  },
  {
    page: 'Mission detail',
    design: 'Mission Detail.dc.html',
    routes: ['missions/$missionId.tsx'],
    copy: [
      'All missions',
      'Share this mission',
      'Chapter',
      'When',
      'Where',
      'Service hours',
      'Added on verification',
      'Mission lead',
      'Roles needed',
      'filled',
      'positions',
      'Helpful skills:',
      'Open to everyone — no specific skills needed',
      'Claim role',
      'Change to this',
      'Your role',
      'Impact report',
      'people supported · published record',
      'Delivered',
      'What changed',
      'See the full impact record',
      'Impact target',
      'Team joined',
      'No one from the platform has claimed a role yet. Be the first.',
      'Your place on this mission',
      'Sign in to My Goodness to claim a role.',
      'Sign in to join',
      'Pick a role on the left to join this mission.',
      "You're on this mission",
      'Check-in code',
      'Show this to your mission lead on the day, or tap below.',
      'Remote contribution',
      "No check-in needed. Start when you're ready, then submit your completion for verification.",
      'Start contribution',
      'Check in now',
      'Submit completion',
      'Your contribution has been submitted for verification.',
      'Hours verified',
      'Leave mission',
      'Leave this mission?',
      'Your position becomes available to another volunteer straight away.',
      'Yes, leave',
      'Keep my place',
      'How it works',
      'Contribution submitted',
      'Your team lead confirms — hours post to your passport.',
    ],
  },
  {
    page: 'Impact',
    design: 'Impact.dc.html',
    routes: ['impact.tsx'],
    copy: [
      "We don't stop at what we delivered.",
      'We measure what changed.',
      'people supported through published impact records. Counted once per record',
      'someone who joins two programmes appears in both records.',
      'Outputs',
      'What we delivered — sessions run, people trained, packs distributed.',
      'Outcomes',
      'What changed because of it — jobs secured, accounts opened, commitments won.',
      'Published records',
      'Fully verified evidence',
      'Output targets met',
      'Outcomes awaiting measurement',
      'Where the work happened',
      'Break it down by',
      'program',
      'Click a program to see the records, targets, outcomes, and the evidence behind each claim.',
      'All published records',
      'Show all programs',
      'published records',
      'Published',
      'Outputs · what we delivered',
      'targets met',
      'No numeric targets set',
      'Outcomes · what changed',
      'Each claim shows how we know it.',
      'Source: ',
      'Evidence',
      'items verified by our team',
      'Verified',
      'Pending',
      'Self-reported',
      'Observed',
      'Awaiting measurement',
      'Evidence verified',
      'Evidence pending',
      'How to read this',
      'Confirmed against a document or third-party record.',
      'Told to us by participants, usually via survey.',
      'Recorded by our team in the field.',
      'Too early to know. We publish the date, not a guess.',
      'Draft records stay internal until published. Publishing a record does not verify it',
      'This is what goodness looks like',
      'when we organize it.',
      'Every number on this page traces back to a mission, a verified volunteer, and a document you can ask to see.',
      'Join a mission',
      'Fund this work',
    ],
  },
  {
    page: 'Trust Ledger',
    design: 'Trust Ledger.dc.html',
    routes: ['trust.tsx'],
    copy: [
      'Trust Ledger · 2026 year to date',
      'Follow every taka',
      'from the donation to the outcome.',
      'Received',
      'recorded donations',
      'Allocated to funds',
      'not yet allocated',
      'budgeted',
      'Accepted into the ledger',
      'recorded, awaiting review',
      'Programme spending',
      'Operations & administration',
      'of accepted spending',
      'of accepted spending has a document attached',
      'fully checked by our team',
      'Figures cover 1 Jan – 31 Aug 2026.',
      'These are our own books, reviewed internally and audited annually.',
      'Step 1 · Allocation',
      'Where the money',
      'is committed',
      'Click a fund to see its budget, every expense against it, the documents behind each one, and the impact record it supported.',
      'accepted',
      'budget',
      'with documents',
      'funding gap',
      'Step 2 · Spending',
      'received as restricted gifts',
      'restricted balance remaining',
      'Funded from unrestricted giving',
      'Budget exceeds allocated funds by',
      'this programme is still seeking funding.',
      'Allocated',
      'Accepted spending',
      'Unspent allocation',
      'Funding gap',
      'Close',
      'Expense',
      'Amount',
      'Payee & date',
      'Documents',
      'Ledger status',
      'Supported:',
      'checked',
      'attached',
      'No document yet',
      'Awaiting review',
      'Step 3 · This spending supported',
      'documents verified',
      'Full record',
      'This fund supported the work above; the recorded impact is not a conversion of taka into outcomes.',
      'Pick a fund above to follow the money through to the work it paid for.',
      'Money in',
      'Every donation',
      'we have recorded',
      'Donor',
      'Date',
      'Restricted to',
      'Receipt issued',
      'Unrestricted',
      'Individual donors are listed by the name they gave us; anyone may ask to appear as an anonymous donor',
      'Restricted gifts can only be spent on the programme named.',
      'Fund a mission and',
      'watch it move through this page.',
      'Your gift is recorded here, allocated to a fund, spent against documented invoices, and tied to the impact record it supported.',
      'Fund this work',
      'See the impact',
    ],
  },
  {
    page: 'Chapters',
    design: 'Chapters.dc.html',
    routes: ['chapters/index.tsx'],
    copy: [
      'The Network',
      'One organisation.',
      'Goodness, everywhere.',
      'Chapters run their own missions with their own leaders',
      'Every number below is computed from the same records as the rest of the platform.',
      'Start a chapter in your city',
      'Active chapters',
      'Forming chapters',
      'Chapter members',
      'Verified hours across the network',
      'Across Goodness right now',
      'is forming — leadership team assembling',
      'more volunteers',
      'published —',
      'people supported',
      'District chapter',
      'University chapter',
      'Forming',
      'under',
      'Members',
      'Missions live',
      'People supported',
      'Partners',
      'Leadership team being established · Goodness standards',
      'Leadership forming',
      'Visit chapter',
      'Follow progress',
      "Don't see Goodness in your city?",
      'Start a chapter.',
      'Chapters begin with a few committed people.',
      'City or campus *',
      'Your name & contact *',
      'Why here? Local needs, your team, your Goodness ID if you have one',
      'Propose the chapter',
      'City and contact are required.',
      'Lifecycle: Proposed → Forming (leadership + Goodness standards) → Active.',
      'Chapter proposal received — HQ reviews it and, if approved, your chapter appears here as Forming. Watch this page.',
    ],
  },
  {
    page: 'Chapter',
    design: 'Chapter.dc.html',
    routes: ['chapters/$chapterId.tsx'],
    copy: [
      '← All chapters',
      'District chapter',
      'University chapter',
      'Forming',
      'under',
      'Members',
      'Verified hours',
      'People supported',
      'Local partners',
      'Deployed locally',
      'Goodness standards',
      'supported by',
      'Needed now',
      'How you can help this chapter this week.',
      'Local partner',
      'Fund or resource',
      'next initiative',
      'Missions in',
      'No missions listed here yet.',
      'Published impact from this chapter',
      "No published impact records yet — nothing is invented before it's measured.",
      'From this chapter',
      'Chapter team',
      'Leadership team being established.',
      'Lead? Chapter Control',
      '2026 goals',
      'Partners powering',
      'No local partners yet — be the first.',
      'Help fund',
      'This is your chapter',
      'Make this my chapter',
      'Help form this chapter',
      'Your primary chapter is where you belong organisationally — you can still join missions anywhere in Goodness.',
      'SHARE THIS CHAPTER:',
      'Proud member',
      'Chapter milestone',
      'Year in review',
      'Recruit founding volunteers',
    ],
  },
  {
    page: 'Our Volunteers',
    design: 'Volunteers.dc.html',
    routes: ['people/index.tsx'],
    copy: [
      'Our Volunteers',
      'Meet our',
      'Change-Makers',
      "Every person here chose to show up. They bring their time, skills, and belief that things can be better — and together, they're proving it.",
      'Get Listed Here',
      'Active Volunteers',
      'Cities Represented',
      'Programs Supported',
      'Verified Service Hours',
      'Featured',
      'View profile',
      'Search by name, skill or city…',
      'volunteer',
      'matching',
      'No volunteers found',
      'Try a different search or filter.',
      'Since',
      'change-makers and counting',
      'Your name',
      'belongs here.',
      'Join a community of professionals, students, and community leaders using their skills to create real, lasting change.',
      'Apply to Volunteer',
      'See Our Programs',
    ],
  },
]
describe.each(CONTRACTS)('$page follows $design', (contract) => {
  const design = normalise(readFileSync(resolve(root, contract.design), 'utf8'))
  const built = normalise(
    contract.routes
      .map((file) => readFileSync(resolve(__dirname, file), 'utf8'))
      .join('\n'),
  )

  it('quotes copy that really is in the design file', () => {
    for (const line of contract.copy) {
      expect(design, `"${line}" is not in ${contract.design}`).toContain(
        normalise(line),
      )
    }
  })

  it('keeps that copy in the build', () => {
    for (const line of contract.copy) {
      expect(built, `"${line}" is missing from the page`).toContain(
        normalise(line),
      )
    }
  })
})
